steps:
- checkout: none

- task: UsePythonVersion@0
  inputs:
    versionSpec: $(PYTHON_VERSION)
  displayName: Use Python $(PYTHON_VERSION)

- task: DownloadBuildArtifacts@0
  displayName: Get pre-built package
  inputs:
    buildType: current
    downloadType: single
    artifactName: package
    downloadPath: $(System.ArtifactsDirectory)

- task: ExtractFiles@1
  displayName: Checkout sources
  inputs:
    archiveFilePatterns: $(System.ArtifactsDirectory)/package/repo-source.tar.gz
    destinationFolder: $(Pipeline.Workspace)/src

- bash: |
    pip install -U pip
    pip install -r "$(Pipeline.Workspace)/src/requirements_dev.txt"
    pip install "$(Pipeline.Workspace)/src"
  displayName: Install package

- bash: |
    PYTHONDEVMODE=1 mypy src tests
  displayName: Run mypy type checker
  workingDirectory: $(Pipeline.Workspace)/src

- bash: |
    PYTHONDEVMODE=1 pytest -ra --cov=$(pwd) --cov=diffcalc --cov-report=xml --cov-branch
  displayName: Run tests
  workingDirectory: $(Pipeline.Workspace)


- bash: |
    curl -Os https://uploader.codecov.io/latest/linux/codecov
    chmod +x codecov
    ./codecov -t $(CODECOV_TOKEN)
  env:
    CODECOV_TOKEN: $(CODECOV_TOKEN)
  displayName: Publish coverage stats
  continueOnError: true
  workingDirectory: $(Pipeline.Workspace)
  timeoutInMinutes: 2
