name: Code CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * MON"

jobs:
  lint:
    steps:
      - uses: actions/checkout@v2
      - uses: weibullguy/python-lint-plus@master
        with:
          use-black: true
          use-mypy: true
          use-flake8: true
          extra-flake8-options: "--ignore=C901,W503,E741"